/**
 * Divination suite — four oracular systems, all drawn from the same entropy
 * stream as the Quantum Seed (drand beacon, CSPRNG fallback):
 *
 *   - Geomancy: full 16-figure shield chart generated by the classical
 *     algorithm (Mothers → Daughters → Nieces → Witnesses → Judge), plus
 *     the Requerant and Sentence derived by figure addition.
 *   - Runes: 24-elder Futhark draw (single / three Norn spread).
 *   - Tarot: 78-card Rider–Waite–Smith deck, upright/reversed,
 *     single card / three-card past–present–future.
 *   - I Ching: six-line coin-method hexagram with King Wen number/name,
 *     changing lines, and the derived second hexagram.
 *
 * Every draw consumes fresh entropy via drawEntropy() so the beacon
 * provenance carries through the whole suite.
 */

import { drawEntropy } from './entropy';

// =====================================================================
// Entropy plumbing
// =====================================================================

/**
 * A bit-stream over freshly drawn entropy. Hex chars → 4 bits each;
 * `bits(n)` returns the next n bits as an integer. The timestamp keeps
 * two draws in the same millisecond from returning identical streams.
 */
async function entropyStream(): Promise<(n: number) => number> {
    const { hex } = await drawEntropy();
    let pos = 0;
    let extra = Math.floor(Math.random() * 0xffffffff);
    return (n: number): number => {
        let v = 0;
        for (let i = 0; i < n; i++) {
            if (pos >= hex.length) {
                extra = (extra * 1664525 + 1013904223) >>> 0;
                v = (v << 1) | (extra & 1);
                extra = (extra >>> 1) | (extra << 31);
                continue;
            }
            const nib = parseInt(hex[pos], 16);
            const bit = (nib >> (3 - (pos % 4))) & 1;
            v = (v << 1) | bit;
            pos++;
        }
        return v;
    };
}

// =====================================================================
// Geomancy
// =====================================================================

/** Geomantic figure: 4 lines, top→bottom = fire, air, water, earth. 1 = active (single point). */
export interface GeoFigure {
    name: string;
    latin: string;
    /** 4 bits, index 0 = fire (top). */
    lines: [number, number, number, number];
    planet: string;
    sign: string;
    element: 'Fire' | 'Air' | 'Water' | 'Earth';
    quality: 'Stable' | 'Mobile';
    omen: string;
    meaning: string;
}

/** Line patterns in Unicode order: Populus (0000) → Via (1111). */
const GEO_PATTERNS: Array<{ name: string; latin: string; lines: [number, number, number, number] }> = [
    { name: 'Populus', latin: 'the People', lines: [0, 0, 0, 0] },
    { name: 'Tristitia', latin: 'Sorrow', lines: [0, 0, 0, 1] },
    { name: 'Albus', latin: 'White', lines: [0, 0, 1, 0] },
    { name: 'Fortuna Major', latin: 'the Greater Fortune', lines: [0, 0, 1, 1] },
    { name: 'Rubeus', latin: 'Red', lines: [0, 1, 0, 0] },
    { name: 'Laetitia', latin: 'Joy', lines: [0, 1, 0, 1] },
    { name: 'Conjunctio', latin: 'the Conjunction', lines: [0, 1, 1, 0] },
    { name: 'Caput Draconis', latin: 'the Head of the Dragon', lines: [0, 1, 1, 1] },
    { name: 'Amissio', latin: 'Loss', lines: [1, 0, 0, 0] },
    { name: 'Carcer', latin: 'the Prison', lines: [1, 0, 0, 1] },
    { name: 'Fortuna Minor', latin: 'the Lesser Fortune', lines: [1, 0, 1, 0] },
    { name: 'Puella', latin: 'the Girl', lines: [1, 0, 1, 1] },
    { name: 'Cauda Draconis', latin: 'the Tail of the Dragon', lines: [1, 1, 0, 0] },
    { name: 'Puer', latin: 'the Boy', lines: [1, 1, 0, 1] },
    { name: 'Via', latin: 'the Way', lines: [1, 1, 1, 0] },
    { name: 'Acquisitio', latin: 'Gain', lines: [1, 1, 1, 1] },
];

const GEO_META: Array<Omit<GeoFigure, 'lines' | 'latin' | 'name'>> = [
    { planet: 'Moon (waxing)', sign: 'Cancer', element: 'Water', quality: 'Stable', omen: 'neutral', meaning: 'The crowd, the many, quiet assembly. Outcomes follow the weight of surrounding figures.' },
    { planet: 'Saturn', sign: 'Aquarius', element: 'Earth', quality: 'Stable', omen: 'ill', meaning: 'The stake driven into the earth. Sorrow, delay — yet favorable for building, stability, and things of the earth.' },
    { planet: 'Mercury', sign: 'Gemini', element: 'Air', quality: 'Stable', omen: 'fair', meaning: 'The upright goblet. Wisdom, purity, careful planning. A weak but well-meaning figure.' },
    { planet: 'Sun (north)', sign: 'Leo', element: 'Fire', quality: 'Stable', omen: 'most favorable', meaning: 'Blessings rising from the earth. Great fortune, long-term success — after hardship at the outset.' },
    { planet: 'Mars (retrograde)', sign: 'Scorpio', element: 'Water', quality: 'Mobile', omen: 'very ill', meaning: 'The overturned glass. Passion, deception, violence. Good in all that is evil, evil in all that is good.' },
    { planet: 'Jupiter (retrograde)', sign: 'Pisces', element: 'Fire', quality: 'Mobile', omen: 'most favorable', meaning: 'The arch, the fountain. Joy, upward motion, fast construction and happy outcomes.' },
    { planet: 'Mercury (retrograde)', sign: 'Virgo', element: 'Air', quality: 'Mobile', omen: 'neutral', meaning: 'The crossroads. Union of forces — good in good things, evil in evil. Favors joining and recovering.' },
    { planet: 'Venus & Jupiter', sign: 'Sagittarius', element: 'Earth', quality: 'Stable', omen: 'favorable at beginnings', meaning: 'The north node. Entering the door. Fortunate for new undertakings; amplifies whatever surrounds it.' },
    { planet: 'Venus (retrograde)', sign: 'Taurus', element: 'Earth', quality: 'Mobile', omen: 'ill', meaning: 'Two bowls overturned. Loss — except where loss is wanted, or in matters of Venus.' },
    { planet: 'Saturn (retrograde)', sign: 'Capricorn', element: 'Earth', quality: 'Stable', omen: 'ill', meaning: 'The prison cell. Binding, delay, immobility — which is also strength. Favorable for security and endurance.' },
    { planet: 'Sun (south)', sign: 'Leo', element: 'Fire', quality: 'Mobile', omen: 'weakly favorable', meaning: 'Light from the sun, briefly. Transient success that depends on outside help. Swift, unstable.' },
    { planet: 'Venus', sign: 'Libra', element: 'Water', quality: 'Stable', omen: 'favorable', meaning: 'The girl at the mirror. Peace, beauty, passivity. It receives rather than acts.' },
    { planet: 'Saturn & Mars', sign: 'Virgo (south node)', element: 'Fire', quality: 'Mobile', omen: 'very ill', meaning: 'The south node. An ending. Good only for closing, banishing, and letting go — the reading itself was once stopped if it fell first.' },
    { planet: 'Mars', sign: 'Aries', element: 'Fire', quality: 'Mobile', omen: 'ill', meaning: 'The sword. Aggression, haste, male force. Good only in love and war.' },
    { planet: 'Moon (waning)', sign: 'Cancer', element: 'Water', quality: 'Mobile', omen: 'neutral', meaning: 'The eternal road. Change above all things — good for journeys, indifferent elsewhere. It inverts every figure it touches.' },
    { planet: 'Jupiter', sign: 'Sagittarius', element: 'Air', quality: 'Stable', omen: 'most favorable', meaning: 'Two bowls upright. Gain, obtaining, something within one\u2019s grasp.' },
];

export const GEO_FIGURES: GeoFigure[] = GEO_PATTERNS.map((p, i) => ({
    ...p,
    ...GEO_META[i],
}));

/** Classical addition: per line, same → 0 (two dots), different → 1 (one dot). XOR. */
export function geoAdd(a: GeoFigure, b: GeoFigure): GeoFigure {
    const lines: [number, number, number, number] = [
        a.lines[0] ^ b.lines[0],
        a.lines[1] ^ b.lines[1],
        a.lines[2] ^ b.lines[2],
        a.lines[3] ^ b.lines[3],
    ];
    return GEO_FIGURES.find(f => f.lines.every((l, i) => l === lines[i]))!;
}

export interface GeoReading {
    mothers: GeoFigure[];
    daughters: GeoFigure[];
    nieces: GeoFigure[];
    witnesses: [GeoFigure, GeoFigure];
    judge: GeoFigure;
    requerant: GeoFigure;
    sentence: GeoFigure;
}

/**
 * Full shield chart. Mothers come from the entropy stream (4 figures ×
 * 4 lines); everything else is derived by the classical algorithm:
 * daughters rotate the mother lines; nieces 1–4 add M1+M2, M3+M4,
 * D1+D2, D3+D4; witnesses add niece pairs; the Judge adds the witnesses
 * (its point count is always even by construction). The Requerant adds
 * the Judge to the First Witness; the Sentence adds the Judge to the
 * First Mother.
 */
export async function castGeomancy(): Promise<GeoReading> {
    const bits = await entropyStream();

    const mothers: GeoFigure[] = [];
    for (let m = 0; m < 4; m++) {
        const lines: [number, number, number, number] = [
            bits(1), bits(1), bits(1), bits(1),
        ];
        mothers.push(GEO_FIGURES.find(f => f.lines.every((l, i) => l === lines[i]))!);
    }

    // Daughters: daughter i takes line i from each mother, top→bottom.
    const daughters: GeoFigure[] = [0, 1, 2, 3].map(i => {
        const lines: [number, number, number, number] = [
            mothers[0].lines[i], mothers[1].lines[i], mothers[2].lines[i], mothers[3].lines[i],
        ];
        return GEO_FIGURES.find(f => f.lines.every((l, j) => l === lines[j]))!;
    });

    const n1 = geoAdd(mothers[0], mothers[1]);
    const n2 = geoAdd(mothers[2], mothers[3]);
    const n3 = geoAdd(daughters[0], daughters[1]);
    const n4 = geoAdd(daughters[2], daughters[3]);
    const w1 = geoAdd(n1, n2);
    const w2 = geoAdd(n3, n4);
    const judge = geoAdd(w1, w2);
    const requerant = geoAdd(judge, w1);
    const sentence = geoAdd(judge, mothers[0]);

    return { mothers, daughters, nieces: [n1, n2, n3, n4], witnesses: [w1, w2], judge, requerant, sentence };
}

// =====================================================================
// Runes — Elder Futhark
// =====================================================================

export interface Rune {
    name: string;
    /** Unicode runic letter. */
    glyph: string;
    aett: 1 | 2 | 3;
    meaning: string;
    merkstave: string;
}

export const ELDER_FUTHARK: Rune[] = [
    { name: 'Fehu', glyph: 'ᚠ', aett: 1, meaning: 'Cattle, mobile wealth. Power earned and circulating; generosity that multiplies.', merkstave: 'Loss, greed, stalled resources' },
    { name: 'Uruz', glyph: 'ᚢ', aett: 1, meaning: 'The aurochs. Untamed strength, vitality, the door through endurance.', merkstave: 'Weakness, missed chances, violence misused' },
    { name: 'Thurisaz', glyph: 'ᚦ', aett: 1, meaning: 'The thorn, the giant. Reactive force, defense, the sharp lesson.', merkstave: 'Danger, betrayal, acting in haste' },
    { name: 'Ansuz', glyph: 'ᚨ', aett: 1, meaning: 'The god-breath. Divine message, inspiration, the signal in noise.', merkstave: 'Miscommunication, trickery, hollow advice' },
    { name: 'Raidho', glyph: 'ᚱ', aett: 1, meaning: 'The ride. Right motion, journeys, rhythm and lawfulness of the path.', merkstave: 'Disruption, rigidity, a journey misdirected' },
    { name: 'Kenaz', glyph: 'ᚲ', aett: 1, meaning: 'The torch. Crafted fire, knowledge opening, the forge of skill.', merkstave: 'Darkness, confusion, creative block' },
    { name: 'Gebo', glyph: 'ᚷ', aett: 1, meaning: 'The gift. Exchange, honor, sacred reciprocity between equals.', merkstave: 'Imbalance in giving, obligation, debt' },
    { name: 'Wunjo', glyph: 'ᚹ', aett: 1, meaning: 'Joy. Harmony, belonging, the wish fulfilled.', merkstave: 'Sorrow, alienation, delusive happiness' },
    { name: 'Hagalaz', glyph: 'ᚺ', aett: 2, meaning: 'Hail. The uncontrolled crystal force — disruption that clears the field.', merkstave: 'Stagnation wrought of chaos' },
    { name: 'Nauthiz', glyph: 'ᚾ', aett: 2, meaning: 'Need. Constraint that teaches; the fire by friction of necessity.', merkstave: 'Deprivation, denial of truth' },
    { name: 'Isa', glyph: 'ᛁ', aett: 2, meaning: 'Ice. Stillness, concentration, the world held fast — a time to see, not act.', merkstave: 'The same: ice has no reverse' },
    { name: 'Jera', glyph: 'ᛃ', aett: 2, meaning: 'The year, the harvest. Right action rewarded in its own season.', merkstave: 'Bad timing, a harvest not yet due' },
    { name: 'Eihwaz', glyph: 'ᛇ', aett: 2, meaning: 'The yew. Axis of life and death, endurance, the initiates\u2019 tree.', merkstave: 'Confusion, fear of transformation' },
    { name: 'Perthro', glyph: 'ᛈ', aett: 2, meaning: 'The lots-cup. Fate, the hidden, divination itself — what is cast remains secret until it surfaces.', merkstave: 'Addiction, stagnation of secrets' },
    { name: 'Algiz', glyph: 'ᛉ', aett: 2, meaning: 'The elk-sedge, the warding hand. Protection, the divine connection guarded.', merkstave: 'Vulnerability, bad counsel, hidden foes' },
    { name: 'Sowilo', glyph: 'ᛊ', aett: 2, meaning: 'The sun. Victory, the guiding will, health and wholeness of purpose.', merkstave: 'False pride, burned-out success' },
    { name: 'Tiwaz', glyph: 'ᛏ', aett: 3, meaning: 'The sky-god\u2019s arrow. Justice, rational victory, the willing sacrifice.', merkstave: 'Injustice, misplaced faith' },
    { name: 'Berkano', glyph: 'ᛒ', aett: 3, meaning: 'The birch. Birth, nurture, the maiden\u2019s vessel of becoming.', merkstave: 'Sterility, carelessness, domestic strife' },
    { name: 'Ehwaz', glyph: 'ᛖ', aett: 3, meaning: 'The horse. Partnership, trust between rider and mount, lawful progress.', merkstave: 'Distrust, betrayal of alliance' },
    { name: 'Mannaz', glyph: 'ᛗ', aett: 3, meaning: 'The self, humankind. Intelligence and interdependence; the divine in the human.', merkstave: 'Self-delusion, the enemy within' },
    { name: 'Laguz', glyph: 'ᛚ', aett: 3, meaning: 'Water. The intuitive current, dreams, what flows beneath.', merkstave: 'Fear of the unseen, drought of feeling' },
    { name: 'Ingwaz', glyph: 'ᛜ', aett: 3, meaning: 'Ing, the seed. Potential held in darkness; the gestation before emergence.', merkstave: 'Impotence, effort without fruit' },
    { name: 'Dagaz', glyph: 'ᛞ', aett: 3, meaning: 'Day. Breakthrough, the synthesis of opposites, awakening at dawn.', merkstave: 'Blinding, a closure unwanted' },
    { name: 'Othala', glyph: 'ᛟ', aett: 3, meaning: 'Ancestral homestead. Inherited power, the hallowed ground of origin.', merkstave: 'Loss of inheritance, servitude to the past' },
];

export interface RuneDraw {
    spread: 'single' | 'norns';
    stones: Array<{ rune: Rune; reversed: boolean; position: string }>;
}

export async function castRunes(spread: 'single' | 'norns'): Promise<RuneDraw> {
    const bits = await entropyStream();
    const positions = spread === 'single' ? ['The Matter'] : ['Past — Urd', 'Present — Verdandi', 'Future — Skuld'];
    const used = new Set<number>();
    const stones = positions.map(position => {
        let idx = bits(5);
        while (idx >= 24 || used.has(idx)) idx = bits(5);
        used.add(idx);
        return { rune: ELDER_FUTHARK[idx], reversed: bits(1) === 1, position };
    });
    return { spread, stones };
}

// =====================================================================
// Tarot — Rider–Waite–Smith, 78 cards
// =====================================================================

export interface TarotCard {
    /** e.g. "The Magician", "Eight of Cups" */
    name: string;
    arcana: 'major' | 'minor';
    suit?: 'Wands' | 'Cups' | 'Swords' | 'Pentacles';
    number?: number;
    keywords: string;
}

const MAJORS: Array<[string, string]> = [
    ['The Fool', 'new beginnings, innocence, the leap of faith'],
    ['The Magician', 'will, manifestation, skill united with purpose'],
    ['The High Priestess', 'intuition, the hidden knowledge, mystery'],
    ['The Empress', 'abundance, creation, the fertile ground'],
    ['The Emperor', 'authority, structure, the father-wall'],
    ['The Hierophant', 'tradition, teaching, the lineage of keys'],
    ['The Lovers', 'union, choice, the alignment of values'],
    ['The Chariot', 'willful victory, control of opposites, momentum'],
    ['Strength', 'courage, the tamed beast, gentle power'],
    ['The Hermit', 'withdrawal, inner light, the lantern of solitude'],
    ['Wheel of Fortune', 'cycles, fate turning, the lucky rotation'],
    ['Justice', 'truth, balance of accounts, cause and effect'],
    ['The Hanged Man', 'surrender, inversion, seeing from the other side'],
    ['Death', 'transformation, the necessary ending, rebirth'],
    ['Temperance', 'blending, the middle path, patient alchemy'],
    ['The Devil', 'bondage, shadow, the chains made of appetite'],
    ['The Tower', 'upheaval, lightning-truth, the structure revealed as false'],
    ['The Star', 'hope, guidance, the water poured without end'],
    ['The Moon', 'illusion, dreams, the tide of the unconscious'],
    ['The Sun', 'joy, clarity, vitality without shadow'],
    ['Judgement', 'awakening, the call, rising from the grave of the past'],
    ['The World', 'completion, the dance at the center, wholeness'],
];

const SUITS: Array<{ suit: TarotCard['suit']; elem: string; rankKeywords: string[] }> = [
    { suit: 'Wands', elem: 'fire — will, passion, enterprise', rankKeywords: ['spark', 'planning', 'expansion', 'foundation', 'contention', 'victory', 'defense', 'speed', 'resilience', 'burden', 'the student’s wand', 'the quest ridden hard', 'mastery within', 'mastery without, the established will'] },
    { suit: 'Cups', elem: 'water — emotion, intuition, relationship', rankKeywords: ['the heart\u2019s offering', 'partnership', 'celebration', 'boredom reappraised', 'loss, grief', 'innocent memory', 'options, dreams', 'leaving, seeking meaning', 'contentment', 'renewal', 'the student’s cup', 'the romantic quest', 'mastery within', 'mastery without, the steady heart'] },
    { suit: 'Swords', elem: 'air — intellect, conflict, truth', rankKeywords: ['clarity won at cost', 'stalemate', 'heartbreak', 'rest', 'defeat, retreat', 'transition', 'stealth, strategy', 'restriction', 'nightmare, anxiety', 'ruin', 'the student’s blade', 'the charge of reason', 'mastery within', 'mastery without, the judged verdict'] },
    { suit: 'Pentacles', elem: 'earth — body, money, the slow craft', rankKeywords: ['the seed of value', 'juggling two worlds', 'craftsmanship', 'holding tight', 'privation', 'generosity', 'patience, assessment', 'mastery of craft', 'independence', 'legacy', 'the student’s coin', 'the steady venture', 'mastery within', 'mastery without, the realm secured'] },
];

export const TAROT_DECK: TarotCard[] = [
    ...MAJORS.map(([name, keywords], i) => ({ name, arcana: 'major' as const, number: i, keywords })),
    ...SUITS.flatMap(s =>
        s.rankKeywords.map((kw, i) => ({
            name: `${i === 0 ? 'Ace' : i < 10 ? ['Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten'][i - 1] : ['Page', 'Knight', 'Queen', 'King'][i - 10]} of ${s.suit}`,
            arcana: 'minor' as const,
            suit: s.suit,
            number: i,
            keywords: `${kw} (${s.elem})`,
        }))
    ),
];

export interface TarotDraw {
    spread: 'single' | 'three';
    cards: Array<{ card: TarotCard; reversed: boolean; position: string }>;
}

export async function castTarot(spread: 'single' | 'three'): Promise<TarotDraw> {
    const bits = await entropyStream();
    const positions = spread === 'single'
        ? ['The Reading']
        : ['Past', 'Present', 'Future'];
    const used = new Set<number>();
    const cards = positions.map(position => {
        let idx = bits(7);
        while (idx >= 78 || used.has(idx)) idx = bits(7);
        used.add(idx);
        return { card: TAROT_DECK[idx], reversed: bits(1) === 1, position };
    });
    return { spread, cards };
}

// =====================================================================
// I Ching — coin method, King Wen numbering
// =====================================================================

export interface HexagramInfo {
    number: number;
    name: string;
    chinese: string;
    /** Unicode hexagram character U+4DC0 + (number-1). */
    glyph: string;
    /** Lines bottom→top: 1 yang, 0 yin. */
    lines: number[];
}

/**
 * King Wen numbers indexed [lower trigram binary][upper trigram binary].
 * Trigram binary value: bottom line ×1, middle ×2, top ×4, yang = 1 —
 * so index 0 = ☷ Kun(Earth), 1 = ☳ Chen(Thunder), 2 = ☵ Kan(Water),
 * 3 = ☱ Tui(Lake), 4 = ☶ Ken(Mountain), 5 = ☲ Li(Fire), 6 = ☴ Sun(Wind),
 * 7 = ☰ Chien(Heaven). Every cell cross-checked against the standard
 * 8×8 matrix and the classical lower/upper assignments of the 64.
 */
const KING_WEN: number[][] = [
    [ 2, 16,  8, 45, 23, 35, 20, 12], // lower Kun   (Earth)
    [24, 51,  3, 17, 27, 21, 42, 25], // lower Chen  (Thunder)
    [ 7, 40, 29, 47,  4, 64, 59,  6], // lower Kan   (Water)
    [19, 54, 60, 58, 41, 38, 61, 10], // lower Tui   (Lake)
    [15, 62, 39, 31, 52, 56, 53, 33], // lower Ken   (Mountain)
    [36, 55, 63, 49, 22, 30, 37, 13], // lower Li    (Fire)
    [46, 32, 48, 28, 57, 50, 18, 44], // lower Sun   (Wind)
    [11, 34,  5, 43, 26, 14,  9,  1], // lower Chien (Heaven)
];
const HEXAGRAM_NAMES: Record<number, [string, string]> = {
    1: ['Qian', 'The Creative'], 2: ['Kun', 'The Receptive'], 3: ['Zhun', 'Difficulty at the Beginning'],
    4: ['Meng', 'Youthful Folly'], 5: ['Xu', 'Waiting'], 6: ['Song', 'Conflict'],
    7: ['Shi', 'The Army'], 8: ['Bi', 'Holding Together'], 9: ['Xiao Chu', 'Small Accumulating'],
    10: ['Lü', 'Treading'], 11: ['Tai', 'Peace'], 12: ['Pi', 'Standstill'],
    13: ['Tong Ren', 'Fellowship'], 14: ['Da You', 'Great Possession'], 15: ['Qian', 'Modesty'],
    16: ['Yu', 'Enthusiasm'], 17: ['Sui', 'Following'], 18: ['Gu', 'Work on the Decayed'],
    19: ['Lin', 'Approach'], 20: ['Guan', 'Contemplation'], 21: ['Shi He', 'Biting Through'],
    22: ['Bi', 'Grace'], 23: ['Bo', 'Splitting Apart'], 24: ['Fu', 'Return'],
    25: ['Wu Wang', 'Innocence'], 26: ['Da Xu', 'Great Accumulating'], 27: ['Yi', 'Nourishment'],
    28: ['Da Guo', 'Great Exceeding'], 29: ['Xi Kan', 'The Abyss'], 30: ['Li', 'Radiance'],
    31: ['Xian', 'Influence'], 32: ['Heng', 'Duration'], 33: ['Dun', 'Retreat'],
    34: ['Da Zhuang', 'Great Power'], 35: ['Jin', 'Progress'], 36: ['Ming Yi', 'Darkening of the Light'],
    37: ['Jia Ren', 'The Family'], 38: ['Kui', 'Opposition'], 39: ['Jian', 'Obstruction'],
    40: ['Xie', 'Deliverance'], 41: ['Sun', 'Decrease'], 42: ['Yi', 'Increase'],
    43: ['Guai', 'Breakthrough'], 44: ['Gou', 'Coming to Meet'], 45: ['Cui', 'Gathering Together'],
    46: ['Sheng', 'Pushing Upward'], 47: ['Kun', 'Oppression'], 48: ['Jing', 'The Well'],
    49: ['Ge', 'Revolution'], 50: ['Ding', 'The Cauldron'], 51: ['Zhen', 'The Arousing'],
    52: ['Gen', 'Keeping Still'], 53: ['Jian', 'Development'], 54: ['Gui Mei', 'The Marrying Maiden'],
    55: ['Feng', 'Abundance'], 56: ['Lü', 'The Wanderer'], 57: ['Xun', 'The Gentle'],
    58: ['Dui', 'The Joyous'], 59: ['Huan', 'Dispersion'], 60: ['Jie', 'Limitation'],
    61: ['Zhong Fu', 'Inner Truth'], 62: ['Xiao Guo', 'Small Exceeding'], 63: ['Ji Ji', 'After Completion'],
    64: ['Wei Ji', 'Before Completion'],
};

function hexagramInfo(lines: number[]): HexagramInfo {
    // lines bottom→top; trigram value: bottom ×1, middle ×2, top ×4, yang=1.
    // Index 0..7 = Kun, Chen, Kan, Tui, Ken, Li, Sun, Chien.
    const lower = lines[0] + 2 * lines[1] + 4 * lines[2];
    const upper = lines[3] + 2 * lines[4] + 4 * lines[5];
    const num = KING_WEN[lower][upper];
    const [chinese, name] = HEXAGRAM_NAMES[num];
    return { number: num, name, chinese, glyph: String.fromCodePoint(0x4dc0 + num - 1), lines: [...lines] };
}

export interface IchingReading {
    /** First hexagram (the situation). */
    primary: HexagramInfo;
    /** Second hexagram if any lines change, else null. */
    secondary: HexagramInfo | null;
    /** Indexes (0 = bottom) of the changing lines. */
    changing: number[];
    /** Coin values bottom→top: 6 old-yin, 7 yang, 8 yin, 9 old-yang. */
    tosses: number[];
}

/** Coin method: three coins per line; 6 = old yin (changing), 9 = old yang (changing). */
export async function castIChing(): Promise<IchingReading> {
    const bits = await entropyStream();
    const lines: number[] = [];
    const tosses: number[] = [];
    const changing: number[] = [];

    for (let i = 0; i < 6; i++) {
        const heads = bits(1) + bits(1) + bits(1); // 0..3 heads
        const value = 6 + heads; // 6,7,8,9
        tosses.push(value);
        const yang = value === 7 || value === 9;
        lines.push(yang ? 1 : 0);
        if (value === 6 || value === 9) changing.push(i);
    }

    const primary = hexagramInfo(lines);
    let secondary: HexagramInfo | null = null;
    if (changing.length > 0) {
        const flipped = lines.map((l, i) => (changing.includes(i) ? 1 - l : l));
        secondary = hexagramInfo(flipped);
    }
    return { primary, secondary, changing, tosses };
}

/** Small helper for the UI: trigram name for a hexagram's lower/upper third. */
export function trigramName(lines: number[], upper: boolean): string {
    const l = upper ? lines.slice(3) : lines.slice(0, 3);
    const v = l[0] + 2 * l[1] + 4 * l[2];
    return ['Kun', 'Chen', 'Kan', 'Tui', 'Ken', 'Li', 'Sun', 'Chien'][v];
}

export const ICHING_TRIGRAMS: Record<string, { glyph: string; nature: string }> = {
    Chien: { glyph: '☰', nature: 'Heaven' }, Tui: { glyph: '☱', nature: 'Lake' },
    Li: { glyph: '☲', nature: 'Fire' }, Chen: { glyph: '☳', nature: 'Thunder' },
    Sun: { glyph: '☴', nature: 'Wind' }, Kan: { glyph: '☵', nature: 'Water' },
    Ken: { glyph: '☶', nature: 'Mountain' }, Kun: { glyph: '☷', nature: 'Earth' },
};
